ZSH_CUSTOM=$HOME/.zsh-custom
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="jgo"

# CASE_SENSITIVE="true"
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"

ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="mm.dd.yyyy"

plugins=(
  autojump
  brew
  catimg
  git
  git-extras
  meteor
  npm
  macos
  wd
  web-search
)
source $ZSH/oh-my-zsh.sh

export PATH="/usr/local/bin:$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export LANG=en_US.UTF-8
export EDITOR='vi'
export SSH_KEYS="~/.ssh/"
export ANDROID_HOME=$HOME/Library/Android/sdk

#ALIASES
. ~/code/dotfiles/aliases/aliases.sh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
